name: terra
version: 0.0.1
repository: https://github.com/cryptoplease/cryptoplease-dart
description: >-
  Terra library to interact with the Solana blockchain

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bip39: ^1.0.6
  convert: ^3.0.1
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  json_annotation: ^4.0.1
  web_socket_channel: ^2.1.0
  elliptic: ^0.3.5
  ecdsa: ^0.0.4
  bech32: ^0.2.1


dev_dependencies:
  borsh: ^0.2.0+1
  build_runner: ^2.1.1
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  jsonrpc_client:
    path: ../jsonrpc_client
  mews_pedantic: ^0.2.1
  test: ^1.17.11
